site_name: MrFlwrz Destiny 2 Guides
site_description: Sherpa advice and guides for activities!
site_url: https://audiolotus.github.io/d2flwrz
site_author: Flowers

theme:
  name: 'material'
  logo: 
  favicon: 
  custom_dir: overrides
  font:
      text: Ubuntu
      code: Ubuntu Mono
  language: en
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
  features:
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.path
    # - navigation.prune
    - navigation.sections
    - content.tooltips

# Extensions
markdown_extensions:
#Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - mdx_breakless_lists  
  - meta  
  - nl2br
  - sane_lists
  - smarty
  - tables
  - toc:
      permalink: true

#Python Markdown Ext
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - awesome-pages
  - callouts
  - embed_file:
      callouts: true
      custom-attributes: 'assets/css/custom_attributes.css'
  - glightbox
  - meta-descriptions
  - search


#hooks:

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
    - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
    - assets/css/admonition.css
    - assets/css/custom_attributes.css
    - assets/css/customization.css

extra:
  SEO: assets/meta/SEO.png

  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/SJujZm2WDw

# nav:
#   - index.md
#   - Tools.md
#   - Raids:
#     - Raids/index.md
#     - Last Wish:
#       - Raids/Last-Wish/index.md
#       - Raids/Last-Wish/1-Kalli.md
#       - Raids/Last-Wish/2-Shuro-Chi.md
#       - Raids/Last-Wish/3-Morgeth.md
#       - Raids/Last-Wish/4-The-Goddamn-Vault.md
#       - Raids/Last-Wish/5-Riven.md
#       - Raids/Last-Wish/6-Queenswalk.md
#     - Deep Stone Crypt:
#       - Raids/Deep-Stone-Crypt/index.md
#       - Raids/Deep-Stone-Crypt/1-Sparrow.md
#       - Raids/Deep-Stone-Crypt/2-Crypt-Security.md
#       - Raids/Deep-Stone-Crypt/3-Atraks-1.md
#       - Raids/Deep-Stone-Crypt/4-Rapture.md
#       - Raids/Deep-Stone-Crypt/5-Taniks.md
