name: Publish docs via GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: MkDocs Github Pages Releaser
        uses: afritzler/mkdocs-gh-pages-action@v9.5.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #GITHUB_DOMAIN: github.myenterprise.com
